### ISSUE TITLE
Copying Bootloader Specifics

### ISSUE THREAD

**Issue by jaredjones** [ishanthilina/USB-FAT32-Bootloader#1]
I was wondering if you could be more specific in step #4 about how to copy the boot loader to the USB drive. I couldn't figure out how to to do it with MKDOSFS so I ended up using DD. The only problem though is that while the USB drive will show the name: "QUASI OS" I am not able to boot it. If I try to boot it from my Macbook Pro or my Intel Ivy Bridge based motherboard it won't show up as bootable. If I select  "Boot from usb" in my UEFI/BIOS it'll skip it and just go straight to loading Windows 8.

So I'm not sure if the boot loader was copied over properly since I used DD.

**Comment by akoimeexx** [comment]
@jaredjones I noticed the same issue, the duplicated command from formatting the drive in step three. I believe dd is the correct way to write the bootloader to the disk.

Do either of your systems support booting from a non-EFI bootloader? You may have to change the settings in your UEFI setup.

**Comment by ammaratef45** [comment]
I have the same issue

**Comment by ishanthilina** [comment]
Hi All,

My bad. Please use the following command to copy the boot.bin . Make sure you map the drives correctly.

`dd if=boot.bin of=/dev/fd0`
