### ISSUE TITLE
please help me professional programmer

### ISSUE THREAD

**Issue by swad-al-lail** [ishanthilina/USB-FAT32-Bootloader#2]
hi professional programmer, i like for the project that is very good,but i have one problem how can copy the code bootloader and code kernel me into the flash memory,i am try and used the virtualbox give me error,and told me not botabled see that image ,please help me i waiting .
![capture](https://cloud.githubusercontent.com/assets/17045947/12783329/b4beb3ce-ca35-11e5-9f50-bdbd34048391.JPG)

**Comment by ishanthilina** [comment]
Hi,

Unfortunately I have no experience in doing this in windows. A little Googling might help you though. In Linux you could use the following command to copy the image.

`dd if=boot.bin of=/dev/fd0`
